version: '3'
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - symfony
###< doctrine/doctrine-bundle ###
  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: database
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DEFAULT_DB_NAME: ${POSTGRES_DB:-app}
      ADMINER_DESIGN: lucas-sandery
    ports:
      - "8080:8080"
    networks:
      - symfony # Docker containers (services) that need to connect to each other should be on the same network.

  php-nginx:
    build:
      context: ./.docker
      dockerfile: Dockerfile-php-nginx
    volumes:
      - ./:/var/www/project/
    ports:
      - 8000:80 # Ports that are exposed, you can connect to port 8001 to port 80 of the container.
    networks:
      - symfony

  php-fpm:
    build: # Info to build the Docker image
      context: ./.docker # Specify where the Dockerfile is located (e.g. in the root directory of the project)
      dockerfile: Dockerfile-php # Specify the name of the Dockerfile
    environment: # You can use this section to set environment variables. But you can also use the .env file.
      - DATABASE_URL=postgresql://app:password@database/app?serverVersion=15&charset=utf8
    volumes:
      - ./:/var/www/project/ # Location of the project for php-fpm. Note this should be the same for NGINX.*
    networks:
      - symfony # Docker containers (services) that need to connect to each other should be on the same network.

#  node-nginx:
#    build:
#      context: ./.docker
#      dockerfile: .docker/Dockerfile-php-nginx
#    volumes:
#      - ./front:/home/node/app/
#    ports:
#      - 8001:80 # Ports that are exposed, you can connect to port 8001 to port 80 of the container.
#    networks:
#      - symfony
  node:
    build: # Info to build the Docker image
      context: ./ # Specify where the Dockerfile is located (e.g. in the root directory of the project)
      dockerfile: .docker/Dockerfile-node # Specify the name of the Dockerfile
    volumes:
      - ./:/app # Location of the project for php-fpm. Note this should be the same for NGINX.*
    ports:
      - 4200:4200
    networks:
      - symfony

networks:
  symfony:

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
