FROM node:20-alpine

RUN mkdir /.npm-global && chown -R node:node /.npm-global
RUN mkdir /app && chown -R node:node /app

ENV NPM_CONFIG_PREFIX=/.npm-global
ENV PATH=$PATH:/.npm-global/bin

WORKDIR  /app

USER node

COPY --chown=node:node ./ ./

RUN npm install -g @angular/cli@17

CMD npm ci && ng serve --host 0.0.0.0 --port 4200